language: php

php:
  - 7.1
  - 7.2
  - nightly

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)